version: "3.3"

services:
  shoppingapp: 
    image: payalbnsl/shoppingapp
    restart: on-failure:10
    networks: 
      - n1
    ports: 
      - 80:9000
    depends_on:
      - mongoClientTemp
  mongodb:
    container_name: mongodb
    restart: on-failure:10
    image: mongo:4.2
    networks:
      - n1
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
  mongoClientTemp:
    image: mongo:4.2
    restart: on-failure:20
    networks:
      - n1
    command: mongo -host mongodb -u mongodb -p mongodb --authenticationDatabase admin  --eval "db.getSiblingDB('levent').createUser({user:'mongodb', pwd:'mongodb', roles:[{role:'readWrite',db:'levent'}]});"
    depends_on:
    - mongodb
networks:
   n1: